### PR TITLE
feat: logging framework for iOS

### PR DESCRIPTION
**Pull request by ogabrielides**
## Issue being fixed or feature implemented
All logs in dash-shared-core should write into the same file as `DSLog` in `DashSync` and be available when user shares logs from their device.

Right now, everything is printed with `prinln!`

## What was done?
The following macros were created:
`log_error!`, `log_warn!` and `log_info!` that can be used with log prefix and with formatted arguments following requirements of tracing-subscriber.

In case of iOS target build, the logs will be appended to the file `CACHE/Logs/processor.log` in Application's folder.
Along with logging in that file, printing on the console is also kept.

In case of non-iOS build, only the print on the console occurs.

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by HashEngineering** [comment]
uACK

**Comment by ogabrielides** [comment]
> uACK

Although, I am not done yet. The PR is still in draft :)

**Comment by pankcuf** [comment]
There was similar [solution] already for logging (https://github.com/dashpay/dash-shared-core/blob/8a8c03caad1a39965cb4f426c2796a72e241992d/dash-spv-masternode-processor/src/bindings/common.rs#L16C1-L17C1)... Why should we have 2?

**Review by Syn-McJ — APPROVED** [review]
Looks great. @pankcuf take a look too, please

**Review by pankcuf — APPROVED** [review]
LGTM

**Pull request merged**
